### ISSUE TITLE
zabbix agent user sudo

### ISSUE THREAD

**Issue by jimr6007** [sergiotocalini/glusix#3]
zabbix agent user needs sudo privs on gluster and glusterd commands

other than that, awesome work, thanks for providing this !!

I guess I add that requirement to the README.

**Comment by sergiotocalini** [comment]
Hi @jimr6007 
Indeed, the scripts sometimes will need sudo privileges to perform some checks.
I will include in the README.md file.
Thanks for your suggestion ;)
Best,
Sergio
